PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>
PREFIX olia: <http://purl.org/olia/olia.owl#>
PREFIX oliasys: <http://purl.org/olia/system.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


INSERT { ?datapos rdf:type ?oliaConcept } 
WHERE {
   ?datapos conll:POS ?tag
   GRAPH <http://purl.org/olia/penn.owl> {
    	?x rdf:type ?z .
    	?x oliasys:hasTag ?tag.
		?z rdfs:subClassOf+ ?oliaConcept.
		FILTER(strstarts(str(?oliaConcept), "http://purl.org/olia/olia")).
  }
}

