# load OLiA Annotation Model for UD POS annotation and the Linking Model
# find all OLiA Concepts which are superclasses of UD Concepts with the given tag

#CREATE SILENT GRAPH <http://purl.org/olia/ud-pos-all.owl>;
#LOAD <http://purl.org/olia/owl/experimental/univ_dep/consolidated/universal_dependencies.owl> INTO GRAPH <http://purl.org/olia/ud-pos-all.owl>;
#LOAD <http://purl.org/olia/owl/stable/ud-pos-link.rdf> INTO GRAPH <http://purl.org/olia/ud-pos-all.owl>;

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>
PREFIX olia: <http://purl.org/olia/olia.owl#>
PREFIX oliasys: <http://purl.org/olia/system.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


INSERT { ?datapos rdf:type ?oliaConcept } #?p #?word ?oliaConcept ?docid ?sid ?iwid 
WHERE {
   ?datapos conll:POS ?tag
   GRAPH <http://purl.org/olia/penn.owl> {
    	?x rdf:type ?z .
    	?x oliasys:hasTag ?tag.
		?z rdfs:subClassOf+ ?oliaConcept.
		FILTER(strstarts(str(?oliaConcept), "http://purl.org/olia/olia")).
#		?s oliasys:hasTag ?o.
#		?s ?p ?o.
#		FILTER(strstarts(str(?o), "NN")).
  }
#  FILTER(strstarts(str(?z), "NN")).
}
#ORDER BY ?x
#  BIND( SUBSTR( str(?a), 60 ) as ?dswid )
#  BIND( STRBEFORE( ?dswid, "#" ) as ?docid )
#  BIND( STRAFTER( ?dswid, "#" ) as ?swid )
#  BIND( STRBEFORE( ?swid, "_" ) as ?sid )
#  BIND( STRAFTER( ?swid, "_" ) as ?wid )
#  BIND( xsd:integer(?wid) as ?iwid )
  
#    bind( ?a as ?swid )
#}
#ORDER BY ?docid ?sid ?iwid 

#DROP GRAPH <http://purl.org/olia/ud-pos-all.owl>


;

